### ISSUE TITLE
missing resource

### ISSUE THREAD

**Issue by maruilian11** [PCLAB/LabWebsite#1]
>Error in event handler for (unknown): TypeError: Cannot read property 'hiding' of undefined
    at Object.adblock_begin.handleHiding (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/adblock_start_chrome.js:104:13)
    at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/adblock_start_common.js:201:12handler @ VM80 extensions::uncaught_exception_handler:8
http://1007.cse.yzu.edu.tw/Content/AssetsBS3/examples/starter-template.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://1007.cse.yzu.edu.tw/Scripts/AssetsBS3/ie10-viewport-bug-workaround.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://1007.cse.yzu.edu.tw/Content/AssetsBS3/img/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://1007.cse.yzu.edu.tw/Content/AssetsBS3/examples/starter-template.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by eric0383** [comment]
wow that is a big problem~  :)

**Comment by eric0383** [comment]
A_____A dont't delete me plz

**Comment by eric0383** [comment]
agree :")

**Comment by PeterDaveHello** [comment]
unrelated message
> Error in event handler for (unknown): TypeError: Cannot read property 'hiding' of undefined
at Object.adblock_begin.handleHiding (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/adblock_start_chrome.js:104:13)
at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/adblock_start_common.js:201:12handler @ VM80 extensions::uncaught_exception_handler:8
