### ISSUE TITLE
website seems not renew?

### ISSUE THREAD

**Issue by maruilian11** [PCLAB/LabWebsite#4]
I already changed the photo, but the picture on website didn't renew.

**Comment by PeterDaveHello** [comment]
Deploy process runs every 15 mins.

**Comment by ky10071517** [comment]
The page of contact us whose pictures aren't not found.

**Comment by q25227393** [comment]
We changed the screens，so let take some pictures again.

**Comment by ky10071517** [comment]
Aren't those pictures in the rullian's server ?

**Comment by BenjaminChangSummer** [comment]
We can get photos from facebook.
I think that put those photos in the /img on github is a good idea. But photos should not be public.

**Comment by maruilian11** [comment]
sorry, i meant the photo on homepage XD
this problem has been solved~
