### ISSUE TITLE
An unnecessary link

### ISSUE THREAD

**Issue by benjamin1021523** [PCLAB/LabWebsite#8]
I think a link's path, "from index to index" is not essential.
Whether I should delete the link or for making layout neatly to keep the link as before?

**Comment by q25227393** [comment]
Which page you say?

**Comment by maruilian11** [comment]
but many website has this function, i think it's ok.

**Comment by benjamin1021523** [comment]
49fa7135468d5d4e3dc13e20ad5c4af18af065ce
